apiVersion: apps/v1
kind: Deployment
metadata:
  name: element
  labels:
    {{- include "element.labels" . | nindent 4 }}
    component: element
spec:
  selector:
    matchLabels:
      {{- include "element.selectorLabels" . | nindent 6 }}
      component: element
  template:
    metadata:
      {{- with .Values.element.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "element.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        component: element
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "element.serviceAccountName" . }}
      {{- with .Values.element.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: element
          {{- with .Values.element.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.element.image.repository }}:{{ .Values.element.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.element.image.pullPolicy }}
          env:
            - name: CSP_EXTRA_SOURCE
              value: "{{ .Values.cspExtraSource }}"
            - name: DOMAIN
              value: "{{ .Values.matrix.serverName }}"
            - name: HOME_SERVER_URL
              value: "https://{{ .Values.matrix.serverName }}/"
            - name: IDENTITY_SERVER_URL
              value: "https://{{ .Values.identity.serverName }}/"
            - name: TZ
              value: "{{ .Values.timezone }}"

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          {{- with .Values.element.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.element.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.element.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.element.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- with .Values.element.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.element.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.element.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
