{{- if .Values.snuba.eapItemsConsumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-eap-items-consumer
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "sentry.component.labels" (dict "component" "snuba-eap-items-consumer" "ctx" .) | nindent 4 }}
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "12"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-eap-items-consumer
  replicas: {{ .Values.snuba.eapItemsConsumer.replicas }}
  template:
    metadata:
      annotations:
        checksum/snubaSettingsPy: {{ .Values.config.snubaSettingsPy | sha256sum }}
        checksum/config.yaml: {{ include "sentry.snuba.config" . | sha256sum }}
        {{- if .Values.snuba.eapItemsConsumer.annotations }}
{{ toYaml .Values.snuba.eapItemsConsumer.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-eap-items-consumer
        {{- include "sentry.component.labels" (dict "component" "snuba-eap-items-consumer" "ctx" .) | nindent 8 }}
        {{- if .Values.snuba.eapItemsConsumer.podLabels }}
{{ toYaml .Values.snuba.eapItemsConsumer.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.snuba.eapItemsConsumer.affinity }}
{{ toYaml .Values.snuba.eapItemsConsumer.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.eapItemsConsumer.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.snuba.eapItemsConsumer.nodeSelector | indent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.eapItemsConsumer.tolerations }}
      tolerations:
{{ toYaml .Values.snuba.eapItemsConsumer.tolerations | indent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.eapItemsConsumer.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml .Values.snuba.eapItemsConsumer.topologySpreadConstraints | indent 8 }}
      {{- end }}
      {{- if .Values.images.snuba.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.snuba.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.eapItemsConsumer.securityContext }}
      securityContext:
{{ toYaml .Values.snuba.eapItemsConsumer.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-snuba
        image: "{{ template "snuba.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.snuba.pullPolicy }}
        command:
          - "snuba"
          - "rust-consumer"
          - "--use-rust-processor"
          - "--storage"
          - "eap_items"
          - "--consumer-group"
          - "eap_items_group"
          {{- if .Values.snuba.eapItemsConsumer.autoOffsetReset }}
          - "--auto-offset-reset"
          - "{{ .Values.snuba.eapItemsConsumer.autoOffsetReset }}"
          {{- end }}
          {{- if .Values.snuba.eapItemsConsumer.maxBatchSize }}
          - "--max-batch-size"
          - "{{ .Values.snuba.eapItemsConsumer.maxBatchSize }}"
          {{- end }}
          {{- if .Values.snuba.eapItemsConsumer.processes }}
          - "--processes"
          - "{{ .Values.snuba.eapItemsConsumer.processes }}"
          {{- end }}
          {{- if .Values.snuba.eapItemsConsumer.inputBlockSize }}
          - "--input-block-size"
          - "{{ .Values.snuba.eapItemsConsumer.inputBlockSize }}"
          {{- end }}
          {{- if .Values.snuba.eapItemsConsumer.outputBlockSize }}
          - "--output-block-size"
          - "{{ .Values.snuba.eapItemsConsumer.outputBlockSize }}"
          {{- end }}
          {{- if .Values.snuba.eapItemsConsumer.maxBatchTimeMs }}
          - "--max-batch-time-ms"
          - "{{ .Values.snuba.eapItemsConsumer.maxBatchTimeMs }}"
          {{- end }}
          {{- if .Values.snuba.eapItemsConsumer.queuedMaxMessagesKbytes }}
          - "--queued-max-messages-kbytes"
          - "{{ .Values.snuba.eapItemsConsumer.queuedMaxMessagesKbytes }}"
          {{- end }}
          {{- if .Values.snuba.eapItemsConsumer.queuedMinMessages }}
          - "--queued-min-messages"
          - "{{ .Values.snuba.eapItemsConsumer.queuedMinMessages }}"
          {{- end }}
          {{- if .Values.snuba.eapItemsConsumer.noStrictOffsetReset }}
          - "--no-strict-offset-reset"
          {{- end }}
          {{- if .Values.snuba.eapItemsConsumer.livenessProbe.enabled }}
          - "--health-check-file"
          - "/tmp/health.txt"
          {{- end }}
        {{- if .Values.snuba.eapItemsConsumer.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command:
              - rm
              - /tmp/health.txt
          initialDelaySeconds: {{ .Values.snuba.eapItemsConsumer.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.snuba.eapItemsConsumer.livenessProbe.periodSeconds }}
        {{- end }}
        ports:
        - containerPort: {{ template "snuba.port" }}
        env:
{{ include "sentry.snuba.env" . | indent 8 }}
{{- if .Values.snuba.eapItemsConsumer.env }}
{{ toYaml .Values.snuba.eapItemsConsumer.env | indent 8 }}
{{- end }}
        envFrom:
        - secretRef:
            name: {{ template "sentry.fullname" . }}-snuba-env
        volumeMounts:
        - mountPath: /etc/snuba
          name: config
          readOnly: true
{{- if .Values.snuba.eapItemsConsumer.volumeMounts }}
{{ toYaml .Values.snuba.eapItemsConsumer.volumeMounts | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.snuba.eapItemsConsumer.resources | indent 12 }}
{{- if .Values.snuba.eapItemsConsumer.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.snuba.eapItemsConsumer.containerSecurityContext | indent 12 }}
{{- end }}
{{- if .Values.snuba.eapItemsConsumer.sidecars }}
{{ toYaml .Values.snuba.eapItemsConsumer.sidecars | indent 6 }}
{{- end }}
{{- if .Values.global.sidecars }}
{{ toYaml .Values.global.sidecars | indent 6 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-snuba
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "sentry.fullname" . }}-snuba
{{- if .Values.snuba.eapItemsConsumer.volumes }}
{{ toYaml .Values.snuba.eapItemsConsumer.volumes | indent 8 }}
{{- end }}
{{- if .Values.global.volumes }}
{{ toYaml .Values.global.volumes | indent 8 }}
{{- end }}
{{- end }}
