{{- if .Values.snuba.subscriptionConsumerEapItems.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-subscription-consumer-eap-items
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "sentry.component.labels" (dict "component" "snuba-subscription-consumer-eap-spans" "ctx" .) | nindent 4 }}
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "18"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "sentry.fullname" . }}
      release: "{{ .Release.Name }}"
      role: snuba-subscription-consumer-eap-items
  replicas: {{ .Values.snuba.subscriptionConsumerEapItems.replicas }}
  template:
    metadata:
      annotations:
        checksum/snubaSettingsPy: {{ .Values.config.snubaSettingsPy | sha256sum }}
        checksum/config.yaml: {{ include "sentry.snuba.config" . | sha256sum }}
        {{- if .Values.snuba.subscriptionConsumerEapItems.annotations }}
{{ toYaml .Values.snuba.subscriptionConsumerEapItems.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-subscription-consumer-eap-items
        {{- include "sentry.component.labels" (dict "component" "snuba-subscription-consumer-eap-items" "ctx" .) | nindent 8 }}
        {{- if .Values.snuba.subscriptionConsumerEapItems.podLabels }}
{{ toYaml .Values.snuba.subscriptionConsumerEapItems.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.snuba.subscriptionConsumerEapItems.affinity }}
{{ toYaml .Values.snuba.subscriptionConsumerEapItems.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.subscriptionConsumerEapItems.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.snuba.subscriptionConsumerEapItems.nodeSelector | indent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.subscriptionConsumerEapItems.tolerations }}
      tolerations:
{{ toYaml .Values.snuba.subscriptionConsumerEapItems.tolerations | indent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.subscriptionConsumerEapItems.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml .Values.snuba.subscriptionConsumerEapItems.topologySpreadConstraints | indent 8 }}
      {{- end }}
      {{- if .Values.images.snuba.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.snuba.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.subscriptionConsumerEapItems.securityContext }}
      securityContext:
{{ toYaml .Values.snuba.subscriptionConsumerEapItems.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-snuba
        image: "{{ template "snuba.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.snuba.pullPolicy }}
        command:
          - "snuba"
          - "subscriptions-scheduler-executor"
          {{- if .Values.snuba.subscriptionConsumerEapItems.autoOffsetReset }}
          - "--auto-offset-reset"
          - "{{ .Values.snuba.subscriptionConsumerEapItems.autoOffsetReset }}"
          {{- end }}
          - "--dataset=events_analytics_platform"
          - "--entity=eap_items"
          {{- if .Values.snuba.subscriptionConsumerEapItems.noStrictOffsetReset }}
          - "--no-strict-offset-reset"
          {{- end }}
          - "--consumer-group=snuba-eap-items-subscriptions-consumers"
          - "--followed-consumer-group=eap_spans_group"
          - "--schedule-ttl=60"
          - "--stale-threshold-seconds=900"
          {{- if .Values.snuba.subscriptionConsumerEapItems.livenessProbe.enabled }}
          - "--health-check-file"
          - "/tmp/health.txt"
          {{- end }}
        {{- if .Values.snuba.subscriptionConsumerEapItems.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command:
              - rm
              - /tmp/health.txt
          initialDelaySeconds: {{ .Values.snuba.subscriptionConsumerEapItems.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.snuba.subscriptionConsumerEapItems.livenessProbe.periodSeconds }}
        {{- end }}
        ports:
        - containerPort: {{ template "snuba.port" }}
        env:
{{ include "sentry.snuba.env" . | indent 8 }}
{{- if .Values.snuba.subscriptionConsumerEapItems.env }}
{{ toYaml .Values.snuba.subscriptionConsumerEapItems.env | indent 8 }}
{{- end }}
        envFrom:
        - secretRef:
            name: {{ template "sentry.fullname" . }}-snuba-env
        volumeMounts:
        - mountPath: /etc/snuba
          name: config
          readOnly: true
{{- if .Values.snuba.subscriptionConsumerEapItems.volumeMounts }}
{{ toYaml .Values.snuba.subscriptionConsumerEapItems.volumeMounts | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.snuba.subscriptionConsumerEapItems.resources | indent 12 }}
{{- if .Values.snuba.subscriptionConsumerEapItems.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.snuba.subscriptionConsumerEapItems.containerSecurityContext | indent 12 }}
{{- end }}
{{- if .Values.snuba.subscriptionConsumerEapItems.sidecars }}
{{ toYaml .Values.snuba.subscriptionConsumerEapItems.sidecars | indent 6 }}
{{- end }}
{{- if .Values.global.sidecars }}
{{ toYaml .Values.global.sidecars | indent 6 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-snuba
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "sentry.fullname" . }}-snuba
{{- if .Values.snuba.subscriptionConsumerEapItems.volumes }}
{{ toYaml .Values.snuba.subscriptionConsumerEapItems.volumes | indent 6 }}
{{- end }}
{{- if .Values.global.volumes }}
{{ toYaml .Values.global.volumes | indent 6 }}
{{- end }}
{{- end }}
