{{- if has "feature-complete" .Values.profiles }}
{{- if .Values.snuba.subscriptionConsumerGenericMetricsGauges.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-subscription-consumer-generic-metrics-gauges
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "sentry.component.labels" (dict "component" "snuba-subscription-consumer-generic-metrics-gauges" "ctx" .) | nindent 4 }}
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "18"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-subscription-consumer-generic-metrics-gauges
  replicas: {{ .Values.snuba.subscriptionConsumerGenericMetricsGauges.replicas }}
  template:
    metadata:
      annotations:
        checksum/snubaSettingsPy: {{ .Values.config.snubaSettingsPy | sha256sum }}
        checksum/config.yaml: {{ include "sentry.snuba.config" . | sha256sum }}
        {{- if .Values.snuba.subscriptionConsumerGenericMetricsGauges.annotations }}
{{ toYaml .Values.snuba.subscriptionConsumerGenericMetricsGauges.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-subscription-consumer-generic-metrics-gauges
        {{- include "sentry.component.labels" (dict "component" "snuba-subscription-consumer-generic-metrics-gauges" "ctx" .) | nindent 8 }}
        {{- if .Values.snuba.subscriptionConsumerGenericMetricsGauges.podLabels }}
{{ toYaml .Values.snuba.subscriptionConsumerGenericMetricsGauges.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.snuba.subscriptionConsumerGenericMetricsGauges.affinity }}
{{ toYaml .Values.snuba.subscriptionConsumerGenericMetricsGauges.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.subscriptionConsumerGenericMetricsGauges.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.snuba.subscriptionConsumerGenericMetricsGauges.nodeSelector | indent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.subscriptionConsumerGenericMetricsGauges.tolerations }}
      tolerations:
{{ toYaml .Values.snuba.subscriptionConsumerGenericMetricsGauges.tolerations | indent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.subscriptionConsumerGenericMetricsGauges.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml .Values.snuba.subscriptionConsumerGenericMetricsGauges.topologySpreadConstraints | indent 8 }}
      {{- end }}
      {{- if .Values.images.snuba.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.snuba.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.subscriptionConsumerGenericMetricsGauges.securityContext }}
      securityContext:
{{ toYaml .Values.snuba.subscriptionConsumerGenericMetricsGauges.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-snuba
        image: "{{ template "snuba.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.snuba.pullPolicy }}
        command:
          - "snuba"
          - "subscriptions-scheduler-executor"
          {{- if .Values.snuba.subscriptionConsumerGenericMetricsGauges.autoOffsetReset }}
          - "--auto-offset-reset"
          - "{{ .Values.snuba.subscriptionConsumerGenericMetricsGauges.autoOffsetReset }}"
          {{- end }}
          - "--dataset=generic_metrics"
          - "--entity=generic_metrics_gauges"
          {{- if .Values.snuba.subscriptionConsumerGenericMetricsGauges.noStrictOffsetReset }}
          - "--no-strict-offset-reset"
          {{- end }}
          - "--consumer-group=snuba-generic-metrics-gauges-subscriptions-schedulers"
          - "--followed-consumer-group=snuba-gen-metrics-gauges-consumers"
          - "--schedule-ttl=60"
          - "--stale-threshold-seconds=900"
          {{- if .Values.snuba.subscriptionConsumerGenericMetricsGauges.livenessProbe.enabled }}
          - "--health-check-file"
          - "/tmp/health.txt"
          {{- end }}
        {{- if .Values.snuba.subscriptionConsumerGenericMetricsGauges.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command:
              - rm
              - /tmp/health.txt
          initialDelaySeconds: {{ .Values.snuba.subscriptionConsumerGenericMetricsGauges.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.snuba.subscriptionConsumerGenericMetricsGauges.livenessProbe.periodSeconds }}
        {{- end }}
        ports:
        - containerPort: {{ template "snuba.port" }}
        env:
{{ include "sentry.snuba.env" . | indent 8 }}
{{- if .Values.snuba.subscriptionConsumerGenericMetricsGauges.env }}
{{ toYaml .Values.snuba.subscriptionConsumerGenericMetricsGauges.env | indent 8 }}
{{- end }}
        envFrom:
        - secretRef:
            name: {{ template "sentry.fullname" . }}-snuba-env
        volumeMounts:
        - mountPath: /etc/snuba
          name: config
          readOnly: true
{{- if .Values.snuba.subscriptionConsumerGenericMetricsGauges.volumeMounts }}
{{ toYaml .Values.snuba.subscriptionConsumerGenericMetricsGauges.volumeMounts | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.snuba.subscriptionConsumerGenericMetricsGauges.resources | indent 12 }}
{{- if .Values.snuba.subscriptionConsumerGenericMetricsGauges.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.snuba.subscriptionConsumerGenericMetricsGauges.containerSecurityContext | indent 12 }}
{{- end }}
{{- if .Values.snuba.subscriptionConsumerGenericMetricsGauges.sidecars }}
{{ toYaml .Values.snuba.subscriptionConsumerGenericMetricsGauges.sidecars | indent 6 }}
{{- end }}
{{- if .Values.global.sidecars }}
{{ toYaml .Values.global.sidecars | indent 6 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-snuba
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "sentry.fullname" . }}-snuba
{{- if .Values.snuba.subscriptionConsumerGenericMetricsGauges.volumes }}
{{ toYaml .Values.snuba.subscriptionConsumerGenericMetricsGauges.volumes | indent 6 }}
{{- end }}
{{- if .Values.global.volumes }}
{{ toYaml .Values.global.volumes | indent 6 }}
{{- end }}
{{- end }}
{{- end }}

