{{- if .Values.drawio.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-drawio-ingress
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: httpd
  annotations:
  {{- if .Values.drawio.ingress.letsencrypt }}
    cert-manager.io/cluster-issuer: "{{ .Values.drawio.ingress.letsencrypt }}"
  {{- end }}
  {{- range $key, $value := .Values.drawio.ingress.configuration }}
    {{- if ($value) }}
    nginx.ingress.kubernetes.io/{{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- with .Values.drawio.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.drawio.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-drawio
            port:
              number: 8080
  {{- if .Values.drawio.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.drawio.hostname }}
    {{- if .Values.drawio.ingress.certificate }}
    secretName: {{ .Values.drawio.ingress.certificate }}
    {{- end  }}
    {{- end  }}
{{- end }}    
