apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx-dpl
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: nginx
  template:
    metadata:
      labels:
        {{- include "appl.selectorLabels" . | nindent 8 }}
        component: nginx
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appl.serviceAccountName" . }}
      containers:
      - name: {{ .Release.Name }}-nginx
        image: eeacms/nginx-taskman:1.25
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: TZ
          value: "{{ .Values.timezone }}"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          {{- toYaml .Values.httpd.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.httpd.securityContext | nindent 12 }}

        {{- if (.Values.httpd.livenessProbe) }}
        livenessProbe:
          {{- toYaml .Values.httpd.livenessProbe | nindent 10 }}
        {{- end }}

        {{- if (.Values.httpd.startupProbe) }}
        startupProbe:
          {{- toYaml .Values.httpd.startupProbe | nindent 10 }}
        {{- end }}

        {{- if (.Values.httpd.readinessProbe) }}
        readinessProbe:
          {{- toYaml .Values.httpd.readinessProbe | nindent 10 }}
        {{- end }}

      volumes:
      - name: nginx-config
        configMap:
          name: {{ .Release.Name }}-nginx-config-cm

      {{- with .Values.httpd.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.httpd.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.httpd.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always

