{{- if .Values.symbolicator.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sentry.fullname" . }}-symbolicator
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "sentry.component.labels" (dict "component" "symbolicator" "ctx" .) | nindent 4 }}
data:
  {{ include "sentry.symbolicator.config" . | nindent 2 }}
{{- end }}
