{{- if gt (int .Values.inferenceCapability.replicaCount) 0 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onyx.fullname" . }}-inference-model
  labels:
    {{- range .Values.inferenceCapability.labels }}
    {{ .key }}: {{ .value }}
    {{- end }}
spec:
  replicas: {{ .Values.inferenceCapability.replicaCount }}
  selector:
    matchLabels:
      {{- range .Values.inferenceCapability.labels }}
      {{ .key }}: {{ .value }}
      {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- range .Values.inferenceCapability.podLabels }}
        {{ .key }}: {{ .value }}
        {{- end }}
    spec:
      {{- if .Values.inferenceCapability.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.inferenceCapability.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- with .Values.inferenceCapability.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $modelRepo := .Values.global.image.repository }}
      {{- if and .Values.inferenceCapability.image .Values.inferenceCapability.image.repository }}
        {{- $modelRepo = .Values.inferenceCapability.image.repository }}
      {{- end }}
      {{- $modelTag := default .Values.global.image.tags.modelServer (printf "model_server-%s" .Values.global.version) }}
      {{- if and .Values.inferenceCapability.image .Values.inferenceCapability.image.tag }}
        {{- $modelTag = .Values.inferenceCapability.image.tag }}
      {{- end }}
      {{- with .Values.inferenceCapability.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.inferenceCapability.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: model-server-inference
        image: "{{ $modelRepo }}:{{ $modelTag }}"
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        command: [ "uvicorn", "model_server.main:app", "--host", "0.0.0.0", "--port", "{{ .Values.inferenceCapability.containerPorts.server }}" ]
        ports:
        - name: model-server
          containerPort: {{ .Values.inferenceCapability.containerPorts.server }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ .Values.config.envConfigMapName }}
        env:
          {{- if .Values.inferenceCapability.huggingfaceCacheDir }}
          - name: HF_HOME
            value: "{{ .Values.inferenceCapability.huggingfaceCacheDir }}"
          {{- end }}
          {{- include "onyx.envSecrets" . | nindent 10 }}
        {{- if .Values.inferenceCapability.securityContext }}
        securityContext:
          {{- toYaml .Values.inferenceCapability.securityContext | nindent 10 }}
        {{- end }}
        {{- if .Values.inferenceCapability.resources }}
        resources:
          {{- toYaml .Values.inferenceCapability.resources | nindent 10 }}
        {{- end }}
        {{- with .Values.inferenceCapability.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.inferenceCapability.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
