apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appl.fullname" . }}-plone
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: plone
spec:
  replicas: {{ .Values.plone.replicaCount }}
  selector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: plone
  template:
    metadata:
      labels:
        {{- include "appl.selectorLabels" . | nindent 8 }}
        component: plone
      {{- with .Values.plone.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appl.serviceAccountName" . }}
      containers:
      - name: plone
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: TZ
          value: "{{ .Values.timezone }}"
        - name: ZOPE_MODE
          value: "{{ .Values.plone.environment.ZOPE_MODE }}"
        - name: ZOPE_THREADS
          value: "{{ .Values.plone.environment.ZOPE_THREADS }}"
        - name: RELSTORAGE_USER
          value: "{{ .Values.postgres.postgres.env.Database.UserName }}"
        - name: RELSTORAGE_PASS
          value: "{{ .Values.postgres.postgres.env.Database.Password }}"
        - name: RELSTORAGE_KEEP_HISTORY
          value: "{{ .Values.plone.environment.RELSTORAGE_KEEP_HISTORY }}"
        - name: SERVER_NAME
          value: "{{ .Values.plone.hostname }}"
        - name: GRAYLOG
          value: "{{ .Values.plone.environment.GRAYLOG }}"
        - name: GRAYLOG_FACILITY
          value: "{{ .Values.plone.hostname }}"
        - name: WARMUP_HEALTH_THRESHOLD
          value: "{{ .Values.plone.environment.WARMUP_HEALTH_THRESHOLD }}"
        - name: STATIC_BANNER_ENABLED
          value: "{{ .Values.plone.environment.STATIC_BANNER_ENABLED }}"
        {{- if .Values.plone.environment.SENTRY_DSN }}
        - name: SENTRY_DSN
          value: "{{ .Values.plone.environment.SENTRY_DSN }}"
        - name: SENTRY_SITE
          value: "{{ .Values.plone.hostname }}"
        {{- end }}
        {{- if .Values.plone.environment.RABBITMQ_HOST }}
        - name: RABBITMQ_HOST
          value: "{{ .Values.plone.environment.RABBITMQ_HOST }}"
        - name: RABBITMQ_USER
          value: "{{ .Values.plone.environment.RABBITMQ_USER }}"
        - name: RABBITMQ_PASS
          value: "{{ .Values.plone.environment.RABBITMQ_PASS }}"
        {{- end }}
        {{- if .Values.plone.environment.CORS_ALLOW_ORIGIN }}
        - name: CORS_ALLOW_ORIGIN
          value: "{{ .Values.plone.environment.CORS_ALLOW_ORIGIN }}"
        {{- end }}
        {{- if .Values.postgres.memcached.enabled }}
        - name: MEMCACHE_SERVER
          value: "{{ include "appl.memcachedHost" . }}:11211"
        {{- end }}
        - name: RELSTORAGE_HOST
          value: "{{ include "appl.postgresHost" . }}"
        ports:
        - name: http
          containerPort: {{ .Values.plone.port }}
        volumeMounts:
        {{- if or .Values.persistence.blobstorage.enabled .Values.persistence.blobstorage.existingClaim }}
        - name: blobstorage
          mountPath: /data/blobstorage
        {{- end }}
        {{- if or .Values.persistence.downloads.enabled .Values.persistence.downloads.existingClaim }}
        - name: downloads
          mountPath: /data/downloads
        {{- end }}
        {{- if or .Values.persistence.suggestions.enabled .Values.persistence.suggestions.existingClaim }}
        - name: suggestions
          mountPath: /data/suggestions
        {{- end }}
        {{- if or .Values.persistence.staticResources.enabled .Values.persistence.staticResources.existingClaim }}
        - name: static-resources
          mountPath: /data/www-static-resources
        {{- end }}
        {{- if .Values.plone.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.plone.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.plone.startupProbe }}
        startupProbe:
          {{- toYaml .Values.plone.startupProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.plone.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.plone.readinessProbe | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.plone.resources | nindent 10 }}
      volumes:
      {{- if or .Values.persistence.blobstorage.enabled .Values.persistence.blobstorage.existingClaim }}
      - name: blobstorage
        {{- if .Values.persistence.blobstorage.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.blobstorage.existingClaim }}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ include "appl.fullname" . }}-blobstorage
        {{- end }}
      {{- end }}
      {{- if or .Values.persistence.downloads.enabled .Values.persistence.downloads.existingClaim }}
      - name: downloads
        {{- if .Values.persistence.downloads.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.downloads.existingClaim }}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ include "appl.fullname" . }}-downloads
        {{- end }}
      {{- end }}
      {{- if or .Values.persistence.suggestions.enabled .Values.persistence.suggestions.existingClaim }}
      - name: suggestions
        {{- if .Values.persistence.suggestions.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.suggestions.existingClaim }}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ include "appl.fullname" . }}-suggestions
        {{- end }}
      {{- end }}
      {{- if or .Values.persistence.staticResources.enabled .Values.persistence.staticResources.existingClaim }}
      - name: static-resources
        {{- if .Values.persistence.staticResources.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.staticResources.existingClaim }}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ include "appl.fullname" . }}-static-resources
        {{- end }}
      {{- end }}
      {{- with .Values.plone.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.plone.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.plone.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
