{{- if and .Values.apache .Values.apache.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dpl-apache
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: apache

spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: apache
  template:
    metadata:
      labels:
        {{- include "appl.selectorLabels" . | nindent 8 }}
        component: apache
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appl.serviceAccountName" . }}
      containers:
      - name: apache
        image: "{{ .Values.apache.image.repository }}:{{ .Values.apache.image.tag }}"
        env:
        - name: TZ
          value: "{{ .Values.timezone }}"
        - name: APACHE_MODULES
          value: "{{ .Values.apache.modules }}"
        - name: APACHE_CONFIG
          value: |
{{ .Values.apache.config | replace "\t" "    " | indent 12 }}

        ports:
        - name: http
          containerPort: 80

        {{- if .Values.apache.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.apache.livenessProbe | nindent 10 }}
        {{- end }}

        {{- if .Values.apache.startupProbe }}
        startupProbe:
          {{- toYaml .Values.apache.startupProbe | nindent 10 }}
        {{- end }}

        resources:
          {{- toYaml .Values.apache.resources | nindent 10 }}

        {{- if .Values.apache.staticContent.enabled }}
        volumeMounts:
        - name: static-content
          mountPath: /staticcontent
        {{- end }}

      {{- if .Values.apache.staticContent.enabled }}
      volumes:
      - name: static-content
        persistentVolumeClaim:
          claimName: {{ .Values.apache.staticContent.existingClaim | default (printf "%s-apache-static" .Release.Name) }}
      {{- end }}

      {{- with .Values.apache.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apache.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apache.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
{{- end }}
