{{- if .Values.globalProxy.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clms-global
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: clms-global
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "cgls.vito.be"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-ssl-server-name: "on"
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.volto.hostname }}
    http:
      paths:
      - path: /global/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: cgls-vito-external
            port:
              number: 443
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.volto.hostname }}
    {{- if .Values.ingress.certificate }}
    secretName: {{ .Values.ingress.certificate }}
    {{- end }}
  {{- end }}
{{- end }}
