apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freshwater-resources
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: freshwater-resources
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/freshwater/(\+\+resource\+\+.*)$ /VirtualHostBase/https/{{ .Values.plone.hostname }}:443/{{ .Values.plone.site }}/VirtualHostRoot/_vh_freshwater/$1 break;
      rewrite ^/freshwater/(\+\+plone\+\+.*)$ /VirtualHostBase/https/{{ .Values.plone.hostname }}:443/{{ .Values.plone.site }}/VirtualHostRoot/_vh_freshwater/$1 break;
      rewrite ^/freshwater/(\+\+theme\+\+.*)$ /VirtualHostBase/https/{{ .Values.plone.hostname }}:443/{{ .Values.plone.site }}/VirtualHostRoot/_vh_freshwater/$1 break;
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.plone.hostname }}
    http:
      paths:
      - path: /freshwater/\+\+resource\+\+(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.varnish.serviceName }}
            port:
              number: {{ .Values.varnish.port }}
      - path: /freshwater/\+\+plone\+\+(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.varnish.serviceName }}
            port:
              number: {{ .Values.varnish.port }}
      - path: /freshwater/\+\+theme\+\+(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.varnish.serviceName }}
            port:
              number: {{ .Values.varnish.port }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.plone.hostname }}
    {{- if .Values.ingress.certificate }}
    secretName: {{ .Values.ingress.certificate }}
    {{- end  }}
  {{- end  }}
