{{- if has "feature-complete" .Values.profiles }}
{{- if .Values.sentry.uptimeResults.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-uptime-results
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "sentry.component.labels" (dict "component" "sentry-subscription-consumer-eap-spans" "ctx" .) | nindent 4 }}
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "10"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
        app: sentry
        release: "{{ .Release.Name }}"
        role: sentry-uptime-results
  replicas: {{ .Values.sentry.uptimeResults.replicas }}
  template:
    metadata:
      annotations:
        checksum/configYml: {{ .Values.config.configYml | toYaml | toString | sha256sum }}
        checksum/sentryConfPy: {{ .Values.config.sentryConfPy | sha256sum }}
        checksum/config.yaml: {{ include "sentry.config" . | sha256sum }}
        {{- if .Values.sentry.uptimeResults.annotations }}
{{ toYaml .Values.sentry.uptimeResults.annotations | indent 8 }}
        {{- end }}
      labels:
        app: sentry
        release: "{{ .Release.Name }}"
        role: sentry-uptime-results
        {{- include "sentry.component.labels" (dict "component" "sentry-uptime-results" "ctx" .) | nindent 8 }}
        {{- if .Values.sentry.uptimeResults.podLabels }}
{{ toYaml .Values.sentry.uptimeResults.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.sentry.uptimeResults.affinity }}
{{ toYaml .Values.sentry.uptimeResults.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.uptimeResults.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.sentry.uptimeResults.nodeSelector | indent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.uptimeResults.tolerations }}
      tolerations:
{{ toYaml .Values.sentry.uptimeResults.tolerations | indent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.uptimeResults.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml .Values.sentry.uptimeResults.topologySpreadConstraints | indent 8 }}
      {{- end }}
      {{- if .Values.images.sentry.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.sentry.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.uptimeResults.securityContext }}
      securityContext:
{{ toYaml .Values.sentry.uptimeResults.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-uptime-results
        image: "{{ template "sentry.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.sentry.pullPolicy }}
        command: ["sentry"]
        args:
          - "run"
          - "consumer"
          - "uptime-results"
          - "--consumer-group"
          - "uptime-results"
          {{- if .Values.sentry.uptimeResults.autoOffsetReset }}
          - "--auto-offset-reset"
          - "{{ .Values.sentry.uptimeResults.autoOffsetReset }}"
          {{- end }}
          {{- if .Values.sentry.uptimeResults.noStrictOffsetReset }}
          - "--no-strict-offset-reset"
          {{- end }}
          {{- if .Values.sentry.uptimeResults.livenessProbe.enabled }}
          - "--healthcheck-file-path"
          - "/tmp/health.txt"
          {{- end }}
        {{- if .Values.sentry.uptimeResults.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command:
              - rm
              - /tmp/health.txt
          initialDelaySeconds: {{ .Values.sentry.uptimeResults.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.sentry.uptimeResults.livenessProbe.periodSeconds }}
        {{- end }}
        env:
{{ include "sentry.env" . | indent 8 }}
{{- if .Values.sentry.uptimeResults.env }}
{{ toYaml .Values.sentry.uptimeResults.env | indent 8 }}
{{- end }}
        volumeMounts:
        - mountPath: /etc/sentry
          name: config
          readOnly: true
        - mountPath: {{ .Values.filestore.filesystem.path }}
          name: sentry-data
        {{- if and (eq .Values.filestore.backend "gcs") .Values.filestore.gcs.secretName }}
        - name: sentry-google-cloud-key
          mountPath: /var/run/secrets/google
        {{ end }}
{{- if .Values.sentry.uptimeResults.volumeMounts }}
{{ toYaml .Values.sentry.uptimeResults.volumeMounts | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.sentry.uptimeResults.resources | indent 12 }}
{{- if .Values.sentry.uptimeResults.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.sentry.uptimeResults.containerSecurityContext | indent 12 }}
{{- end }}
{{- if .Values.sentry.uptimeResults.sidecars }}
{{ toYaml .Values.sentry.uptimeResults.sidecars | indent 6 }}
{{- end }}
{{- if .Values.global.sidecars }}
{{ toYaml .Values.global.sidecars | indent 6 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-uptime-results
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "sentry.fullname" . }}-sentry
      - name: sentry-data
      {{- if and (eq .Values.filestore.backend "filesystem") .Values.filestore.filesystem.persistence.enabled (.Values.filestore.filesystem.persistence.persistentWorkers) }}
      {{- if .Values.filestore.filesystem.persistence.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.filestore.filesystem.persistence.existingClaim }}
      {{- else }}
        persistentVolumeClaim:
          claimName: {{ template "sentry.fullname" . }}-data
      {{- end }}
      {{- else }}
        emptyDir: {}
      {{ end }}
      {{- if and (eq .Values.filestore.backend "gcs") .Values.filestore.gcs.secretName }}
      - name: sentry-google-cloud-key
        secret:
          secretName: {{ .Values.filestore.gcs.secretName }}
      {{ end }}
{{- if .Values.sentry.uptimeResults.volumes }}
{{ toYaml .Values.sentry.uptimeResults.volumes | indent 6 }}
{{- end }}
{{- if .Values.global.volumes }}
{{ toYaml .Values.global.volumes | indent 6 }}
{{- end }}
      {{- if .Values.sentry.uptimeResults.priorityClassName }}
      priorityClassName: "{{ .Values.sentry.uptimeResults.priorityClassName }}"
      {{- end }}
{{- end }}
{{- end }}
