{{- $labels := ( include "appl.labels" . ) -}}
{{- $hostname := .Values.volto.hostname -}}
{{- $varnish := .Values.varnish -}}
{{- range $index, $redirect := .Values.ingressredirects }}
{{- if ($redirect.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eea-website-redirect-{{ $index }}
  labels:
    {{- $labels | nindent 4 }}
    component: eea-website-frontend
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://{{ $hostname }}
  {{- with $redirect.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  ingressClassName: nginx
  rules:
  - host: {{ $redirect.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $varnish.serviceName }}
            port:
              number: {{ $varnish.port }}
  {{- if $redirect.tls }}
  tls:
  - hosts:
    - {{ $redirect.hostname }}
    {{- if $redirect.certificate }}
    secretName: {{ $redirect.certificate }}
    {{- end  }}
  {{- end  }}
---
{{- end }}
{{- end }}
