imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

timezone: Europe/Copenhagen

links:
  database: plone-postgres.namespace

commonEnv:
  ALLOWED_HOSTS: ""
  DEFAULT_FROM_EMAIL: ""
  DJANGO_COLLECT_STATIC: ""
  DJANGO_INDEX_CONTENT: ""
  DJANGO_MIGRATE: ""
  ELASTICSEARCH_AUTH: ""
  ELASTICSEARCH_HOST: ""
  EMAIL_BACKEND: ""
  EMAIL_PORT: ""
  MATOMO: ""
  POSTGRES_DB: ""
  POSTGRES_PASSWORD: ""
  PGPASSWORD: ""
  POSTGRES_USER: ""
  SECRET_KEY: ""
  SENTRY_AUTH_TOKEN: ""
  SENTRY_DSN: ""
  SENTRY_API_URL: ""
  SENTRY_TAG_ENVIRONMENT: ""
  SENTRY_TAG_RELEASE: ""
  SENTRY_TAG_SITE: ""
  SITE_URL: ""
  SUPPORT_EMAIL: ""
  TIMEOUT: ""
  UWSGI_PORT: ""
  POSTGRES_EXPLORER_PASSWORD: ""
  POSTGRES_EXPLORER_USER: ""
  EXCLUDE_REPORTS_IDS: ""
  PUBLIC_REPORTS_IDS: ""

image:
  repository: eeacms/copernicus-insitu-db
  tag: "3.0.6"
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: appsec-nginx
  letsencrypt: 01dev-eea-letsencrypt
  annotations: {}
  host: cis2.eea.europa.eu
  tls: true
  certificate: cis2.eea.europa.eu-tls

persistence:
  staticfiles:
    enabled: true
    existingClaim: ""
    storageClassName: ""
    accessModes:
      - ReadWriteMany
    size: 10Gi
  logging:
    enabled: true
    existingClaim: ""
    storageClassName: ""
    accessModes:
      - ReadWriteMany
    size: 5Gi

web:
  replicaCount: 2
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 2Gi
  env:
    LOGSPOUT: ""
    API_PREFIX: ""
    dianaboiangiu: ""
  nodeSelector: {}
  tolerations: []
  affinity: {}

cron:
  replicaCount: 1
  command:
    - ./docker-entrypoint.cron.sh
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 1Gi
  env:
    DEBUG: ""
    ELASTICSEARCH_TIMEOUT: ""
    API_TOKEN: ""
  nodeSelector: {}
  tolerations: []
  affinity: {}

backupdb:
  enabled: true
  image:
    repository: postgres
    tag: "13-buster"
    pullPolicy: IfNotPresent
  schedule: "0 0 * * 0"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  resources:
    requests:
      memory: 64Mi
    limits:
      memory: 512Mi
  env:
    POSTGRES_DB: ""
    PGPASSWORD: ""
    POSTGRES_USER: ""
  command: >-
    mkdir -p /var/local/static/protected && pg_dump --no-owner --exclude-table=public.explorer_* --inserts -h $POSTGRES_HOST -U $POSTGRES_USER $POSTGRES_DB | gzip > /var/local/static/protected/database.sql.gz
  nodeSelector: {}
  tolerations: []
  affinity: {}

postfix:
  fullnameOverride: ""
  dryrun: false
  serverName: ""
  mtpPass: ""
  mtpPort: ""
  mtpRelay: ""
  mtpUser: ""
  serviceName: "postfix"
  mailtrap:
    httpenabled: false
    serviceType: NodePort
    ingress:
      enabled: false
      hostname: mailtrap.01dev.eea.europa.eu
      annotations:
        cert-manager.io/cluster-issuer: 01dev-eea-letsencrypt
      certificate: mailtrap.01dev.eea.europa.eu-tls
  image:
    repository: eeacms/postfix
    tag: "3.5-1.0"
  resources:
    requests:
      memory: 64Mi
    limits:
      memory: 64Mi
  timezone: Europe/Copenhagen

webserver:
  replicaCount: 1
  image:
    repository: nginx
    tag: "alpine"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      memory: 64Mi
    limits:
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
