{{- if .Values.grafana.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "traefik.grafanaName" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "traefik.grafanaName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://{{ include "traefik.prometheusName" . }}:{{ .Values.prometheus.service.port }}
        isDefault: true
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: traefik
        orgId: 1
        type: file
        disableDeletion: true
        allowUiUpdates: true
        folder: ""
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "traefik.grafanaName" . }}-dashboard
  labels:
    app.kubernetes.io/name: {{ include "traefik.grafanaName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  traefik.json: |
{{ .Values.grafana.dashboardJson | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "traefik.grafanaName" . }}
  labels:
    app.kubernetes.io/name: {{ include "traefik.grafanaName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "traefik.grafanaName" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "traefik.grafanaName" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.grafana.image }}
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.adminUser | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.grafana.service.port }}
              protocol: TCP
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
              subPath: datasource.yaml
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              subPath: dashboards.yaml
            - name: grafana-dashboard
              mountPath: /var/lib/grafana/dashboards/traefik.json
              subPath: traefik.json
            - name: grafana-data
              mountPath: /var/lib/grafana
          resources:
{{ toYaml .Values.grafana.resources | indent 12 }}
      volumes:
        - name: grafana-config
          configMap:
            name: {{ include "traefik.grafanaName" . }}-config
        - name: grafana-dashboard
          configMap:
            name: {{ include "traefik.grafanaName" . }}-dashboard
        - name: grafana-data
{{- if .Values.grafana.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "traefik.grafanaName" . }}
{{- else }}
          emptyDir: {}
{{- end }}
{{- if .Values.grafana.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "traefik.grafanaName" . }}
  labels:
    app.kubernetes.io/name: {{ include "traefik.grafanaName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.grafana.persistence.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.grafana.persistence.storageClass }}
  storageClassName: {{ .Values.grafana.persistence.storageClass | quote }}
{{- end }}
  accessModes:
{{ toYaml .Values.grafana.persistence.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "traefik.grafanaName" . }}
  labels:
    app.kubernetes.io/name: {{ include "traefik.grafanaName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.grafana.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "traefik.grafanaName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: grafana
{{- end }}
