{{- if .Values.prometheus.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "traefik.prometheusName" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "traefik.prometheusName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}
    scrape_configs:
      - job_name: traefik
        static_configs:
          - targets:
              - "{{ include "traefik.fullname" . }}:{{ .Values.traefik.service.metricsPort }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "traefik.prometheusName" . }}
  labels:
    app.kubernetes.io/name: {{ include "traefik.prometheusName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "traefik.prometheusName" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "traefik.prometheusName" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: prometheus
    spec:
      containers:
        - name: prometheus
          image: {{ .Values.prometheus.image }}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.retention.time={{ .Values.prometheus.retention }}"
            - "--storage.tsdb.path=/prometheus"
          ports:
            - name: http
              containerPort: {{ .Values.prometheus.service.port }}
              protocol: TCP
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-data
              mountPath: /prometheus
          resources:
{{ toYaml .Values.prometheus.resources | indent 12 }}
      volumes:
        - name: prometheus-config
          configMap:
            name: {{ include "traefik.prometheusName" . }}-config
        - name: prometheus-data
{{- if .Values.prometheus.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "traefik.prometheusName" . }}
{{- else }}
          emptyDir: {}
{{- end }}
{{- if .Values.prometheus.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "traefik.prometheusName" . }}
  labels:
    app.kubernetes.io/name: {{ include "traefik.prometheusName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.prometheus.persistence.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.prometheus.persistence.storageClass }}
  storageClassName: {{ .Values.prometheus.persistence.storageClass | quote }}
{{- end }}
  accessModes:
{{ toYaml .Values.prometheus.persistence.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.prometheus.persistence.size }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "traefik.prometheusName" . }}
  labels:
    app.kubernetes.io/name: {{ include "traefik.prometheusName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.prometheus.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "traefik.prometheusName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: prometheus
{{- end }}
