apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appl.mailserverName" . }}
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: mailserver
spec:
  replicas: {{ .Values.mailserver.replicaCount }}
  selector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: mailserver
  template:
    metadata:
      labels:
        {{- include "appl.selectorLabels" . | nindent 8 }}
        component: mailserver
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appl.serviceAccountName" . }}
      containers:
        - name: mailserver
          image: "{{ .Values.mailserver.image.repository }}:{{ .Values.mailserver.image.tag }}"
          imagePullPolicy: {{ .Values.mailserver.image.pullPolicy }}
          ports:
            - name: smtp
              containerPort: {{ .Values.mailserver.service.port }}
              protocol: TCP
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
            {{- range $key, $value := .Values.mailserver.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if or .Values.secrets.create .Values.secrets.existingSecret }}
          envFrom:
            - secretRef:
                name: {{ include "appl.secretName" . }}
          {{- end }}
          resources:
            {{- toYaml .Values.mailserver.resources | nindent 12 }}
      {{- with .Values.mailserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mailserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mailserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
