apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appl.webserverName" . }}
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: webserver
spec:
  replicas: {{ .Values.webserver.replicaCount }}
  selector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: webserver
  template:
    metadata:
      labels:
        {{- include "appl.selectorLabels" . | nindent 8 }}
        component: webserver
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appl.serviceAccountName" . }}
      containers:
        - name: webserver
          image: "{{ .Values.webserver.image.repository }}:{{ .Values.webserver.image.tag }}"
          imagePullPolicy: {{ .Values.webserver.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.webserver.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.webserver.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: staticfiles
              mountPath: /var/local/static
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "appl.webserverName" . }}-nginx
        - name: staticfiles
          {{- if or .Values.persistence.staticfiles.enabled .Values.persistence.staticfiles.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ include "appl.staticClaimName" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.webserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
