{{- if .Values.debug.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dpl-debug
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: debug

spec:
  selector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: debug

  template:
    metadata:
      labels:
        {{- include "appl.selectorLabels" . | nindent 8 }}
        component: debug
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appl.serviceAccountName" . }}
      containers:
      - name: debug
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        args:
        - cat
        env:
        - name: SERVER_NAME
          value: "{{ .Values.plone.hostname }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        - name: ZEO_ADDRESS
          value: "{{ .Release.Name }}-zeoserver:8100"
        - name: MEMCACHE_SERVER
          value: "memcached:11211"
        {{- range $key, $value := .Values.plone.environment }}
        {{- if ($value) }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}

        ports:
        - containerPort: 8080

        stdin: true
        tty: true

        resources:
          {{- toYaml .Values.debug.resources | nindent 10 }}

      restartPolicy: Always
{{- end }}
