apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-memcached
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: memcached

spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: memcached
  template:
    metadata:
      labels:
        {{- include "appl.selectorLabels" . | nindent 8 }}
        component: memcached
    spec:
      containers:
      - name: memcached
        image: "{{ .Values.memcached.image.repository }}:{{ .Values.memcached.image.tag }}"
        command:
        - memcached
        - -m
        - "{{ .Values.memcached.maxMemory }}"
        - -I
        - "{{ .Values.memcached.maxItemSize }}"
        env:
        - name: TZ
          value: {{ .Values.timezone }}
        ports:
        - containerPort: 11211
          protocol: TCP
        resources:
          {{- toYaml .Values.memcached.resources | nindent 10 }}
      restartPolicy: Always
