apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zeoserver
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: zeoserver

spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: zeoserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "appl.selectorLabels" . | nindent 8 }}
        component: zeoserver
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appl.serviceAccountName" . }}

      containers:
      - name: zeoserver
        image: "{{ (.Values.zeoserver.image).repository | default "eeacms/marine-backend" }}:{{ (.Values.zeoserver.image).tag | default "0.14.0" }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: TZ
          value: {{ .Values.timezone }}
        - name: ZOPE_MODE
          value: zeo
        resources:
          {{- toYaml .Values.zeoserver.resources | nindent 10 }}

        volumeMounts:
        - mountPath: /data
          name: {{ .Release.Name }}-storage

      {{- with .Values.zeoserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.zeoserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.zeoserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always

      volumes:
      - name: {{ .Release.Name }}-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-storage
