apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-flower
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.flower.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/component: flower
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/component: flower
    spec:
      containers:
      - name: flower
        image: "{{ .Values.flower.image.repository }}:{{ .Values.flower.image.tag }}"
        imagePullPolicy: {{ .Values.flower.image.pullPolicy }}
        env:
        - name: AIRFLOW__API__AUTH_BACKEND
          value: "{{ .Values.flower.env.AIRFLOW__API__AUTH_BACKEND }}"
        - name: AIRFLOW__CELERY__BROKER_URL
          value: "{{ .Values.flower.env.AIRFLOW__CELERY__BROKER_URL }}"
        - name: AIRFLOW__CELERY__RESULT_BACKEND
          value: "{{ .Values.flower.env.AIRFLOW__CELERY__RESULT_BACKEND }}"
        - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
          value: "{{ .Values.flower.env.AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION }}"
        - name: AIRFLOW__CORE__DAG_CONCURRENCY
          value: "{{ .Values.flower.env.AIRFLOW__CORE__DAG_CONCURRENCY }}"
        - name: AIRFLOW__CORE__EXECUTOR
          value: "{{ .Values.flower.env.AIRFLOW__CORE__EXECUTOR }}"
        - name: AIRFLOW__CORE__FERNET_KEY
          value: "{{ .Values.flower.env.AIRFLOW__CORE__FERNET_KEY }}"
        - name: AIRFLOW__CORE__LOAD_EXAMPLES
          value: "{{ .Values.flower.env.AIRFLOW__CORE__LOAD_EXAMPLES }}"
        - name: AIRFLOW__CORE__PARALLELISM
          value: "{{ .Values.flower.env.AIRFLOW__CORE__PARALLELISM }}"
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: "{{ .Values.flower.env.AIRFLOW__CORE__SQL_ALCHEMY_CONN }}"
        - name: TZ
          value: "{{ .Values.flower.env.TZ }}"
        volumeMounts:
        - name: custom-config
          mountPath: /custom_config
        - name: airflow-logs
          mountPath: /opt/airflow/logs
        resources:
          limits:
            memory: "{{ .Values.flower.resources.limits.memory }}"
          requests:
            memory: "{{ .Values.flower.resources.requests.memory }}"
        command:
        - airflow
        - celery
        - flower
        ports:
        - containerPort: 5555
      volumes:
      - name: custom-config
        persistentVolumeClaim:
          claimName: {{ (index .Values.flower.volumes 0).persistentVolumeClaim.claimName }}
      - name: airflow-logs
        persistentVolumeClaim:
          claimName: {{ (index .Values.flower.volumes 1).persistentVolumeClaim.claimName }}
