---
{{- if .Values.sourcemaps.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sentry.fullname" . }}-memcached
  labels:
    {{- include "sentry.component.labels" (dict "component" "memcached" "ctx" .) | nindent 4 }}
data:
  MEMCACHED_MEMORY_LIMIT: "{{ .Values.memcached.memoryLimit }}"
  MEMCACHED_MAX_ITEM_SIZE: "{{ .Values.memcached.maxItemSize }}"
{{- end }}
