{{- if .Values.asyncjobs.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dpl-asyncjobs
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: asyncjobs

spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: asyncjobs

  template:
    metadata:
      labels:
        {{- include "appl.selectorLabels" . | nindent 8 }}
        component: asyncjobs
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appl.serviceAccountName" . }}
      containers:
      - name: asyncjobs
        image: "{{ .Values.asyncjobs.image.repository }}:{{ .Values.asyncjobs.image.tag }}"
        env:
        - name: TZ
          value: "{{ .Values.timezone }}"
        - name: PLONE_URL
          value: "http://backend-plone:8080/{{ .Values.plone.site }}"
        - name: PORT
          value: "3100"
        - name: REDIS_DB
          value: "0"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        {{- range $key, $value := .Values.asyncjobs.environment }}
        {{- if ($value) }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}

        ports:
        - name: http
          containerPort: 3100

        resources:
          {{- toYaml .Values.asyncjobs.resources | nindent 10 }}

      {{- with .Values.asyncjobs.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.asyncjobs.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.asyncjobs.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always

{{- end }}
